### ISSUE TITLE
Needs refactoring to consider dark mode for 6.0 Next

### ISSUE THREAD

**Issue by joshuajaharwood** [elementary-tweaks/elementary-tweaks#153]
The daily builds of Elementary now include dark mode, with selectable accent colours. 

**'Prefer dark variant'** can be removed as it and the accent colours work fine with the GTK theme selector.

Additionally, no build target is available for Elementary/next, the only way to use this right now is to compile from git.

**Comment by ryonakano** [comment]
Actually, this project is in migration to [pantheon-tweaks](https://github.com/pantheon-tweaks/pantheon-tweaks) and the label for that setting looks like this considering the official support for dark mode:

![Screenshot from 2020-09-11 12-46-46](https://user-images.githubusercontent.com/26003928/92855139-ea029e80-f42c-11ea-9913-fafbe92c6b74.png)

I considered removing the setting but it still available for apps that does not support the official dark mode, like Google Chrome, Slack, Visual Studio Code, etc. If you prefer forcing the "perfect dark mode" in elementary OS, it would be helpful.

> Additionally, no build target is available for Elementary/next, the only way to use this right now is to compile from git.

This should be due to some base settings in elementary OS 6 and would not possible to fix within the scope of elementary-tweaks; it's still daily build so there might be some settings that the developers want to make ready just before the final (or beta) release.
