### ISSUE TITLE
Switchboard window resizing is broken when elementary-tweaks is installed

### ISSUE THREAD

**Issue by pridumkuvatyj** [elementary-tweaks/elementary-tweaks#154]
When the elementary-tweaks package is installed, the Switchboard window can't be resized vertically to fit the 1366*768 laptop screen. Also the window can't be maximized to fullscreen.
After package removal the window becomes normally resizable.

Saw it on Elementary OS Juno and now on Hera 5.1.7.
The problem is also described here: https://elementaryos.stackexchange.com/questions/22726/system-settings-window-resize

Anyway, thanks for this useful plugin :)

**Comment by ryonakano** [comment]
elementary-tweaks does not modifies anything about window size, so it's not scope of elementary-tweaks.

Instead, it would be due to System Settings itself. There were similar issues (elementary/switchboard#176 and elementary/switchboard#153) and it seems to be fixed in elementary/switchboard#178. However, this fix (merged on 30 Jun) is not available in the latest stable version released to Hera (released on 1 May).

A new release of System Settings that include this fix may not be released for Hera and you might need to be patient until the next major version of elementary OS called Odin, because they already changed the release target to it in their [release automation file](https://github.com/elementary/switchboard/blob/120d12d3ef3c6c016849743ebb7c2c02bf0ebc41/.github/workflows/release.yml#L19).
