### ISSUE TITLE
Remove elementary-tweaks-1.0.1 properly

### ISSUE THREAD

**Issue by redstrike** [elementary-tweaks/elementary-tweaks#28]
At first, I have installed elementary-tweaks by:

```sh
# Install i-hate-farms repository (not necessary if already done)
curl -sL  http://i-hate-farms.github.io/spores/install | sudo bash - 
sudo apt-get install elementary-tweaks
```
Then I notice that the keyboard settings in System Settings cannot open anymore. So I tried to remove elementary-tweaks and this issue https://github.com/I-hate-farms/elementary-tweaks/issues/14 still haunting me. So I tried to re-install elementary-tweaks by:
```sh
sudo add-apt-repository ppa:philip.scott/elementary-tweaks && sudo apt-get update
sudo apt-get install elementary-tweaks
```
But no hope, the keyboard settings still cannot be opened and the new elementary-tweaks cannot be removed properly.

How can I fix this problem?

**Comment by embik** [comment]
Are you sure you have

* Removed the old (i-hate-farms) repository
* Removed the old elementary-tweaks version
* Made sure the version going to be installed is from the PPA

? Sounds a bit like #18 and #22 to be honest.

**Comment by redstrike** [comment]
I didn't fully remove the i-hate-farms repo, and did it. Then I:
```sh
sudo apt-get remove elementary-tweaks

Removing elementary-tweaks (1.0.1) ...
Processing triggers for libglib2.0-0:amd64 (2.42.2-0ubuntu1~14.04~ricotz0) ...
sh: 1: /usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher: not found
E: Problem executing scripts DPkg::Post-Invoke '/usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher'
E: Sub-process returned an error code
```
Remove and re-add **ppa:philip.scott/elementary-tweaks** for sure, and update:
```sh
sudo apt-get update

W: Failed to fetch http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
And install:
```sh
sudo apt-get install elementary-tweaks

Reading package lists... Done
Building dependency tree        
Reading state information... Done
Package elementary-tweaks is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'elementary-tweaks' has no installation candidate
```

**Comment by Philip-Scott** [comment]
@redstrike This version of elementary tweaks currently only supports the beta release of Loki, and it looks like you're using Freya hence the *trusty* in `Failed to fetch .../elementary-tweaks/ubuntu/dists/trusty/main/...` 
The one by i-hate-farms the the Freya version (But sadly it does have that problem when you try to remove it... :disappointed: ) 

You might have to remove this ppa via `sudo add-apt-repository ppa:philip.scott/elementary-tweaks -r` 

if you run `switchboard` from the terminal, what output do you get when you try to open the keyboard settings?

**Comment by redstrike** [comment]
```sh
$ switchboard

** (switchboard:22056): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-DGhCKrCvlb: Connection refused
[_LOG_LEVEL_INFO 11:03:14.039419] Application.vala:155: System Settings version: 2.0
[_LOG_LEVEL_INFO 11:03:14.039467] Application.vala:157: Kernel version: 3.19.0-65-generic
Segmentation fault (core dumped)

$ switchboard keyboard

** (switchboard:22456): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-DGhCKrCvlb: Connection refused
[_LOG_LEVEL_INFO 11:12:43.362653] Application.vala:155: System Settings version: 2.0
[_LOG_LEVEL_INFO 11:12:43.362687] Application.vala:157: Kernel version: 3.19.0-65-generic
Segmentation fault (core dumped)
```

**Comment by embik** [comment]
As @Philip-Scott pointed out this isn't really related to this version of elementary-tweaks (as it's only available for Loki, not Freya), but we can try to fix your system anyway for documentation's sake.

Quoting the error message from above:

```
sudo apt-get remove elementary-tweaks

Removing elementary-tweaks (1.0.1) ...
Processing triggers for libglib2.0-0:amd64 (2.42.2-0ubuntu1~14.04~ricotz0) ...
sh: 1: /usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher: not found
E: Problem executing scripts DPkg::Post-Invoke '/usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher'
E: Sub-process returned an error code
```

Looks like elementary-tweaks from i-hate-farms doesn't get removed because there's a script missing (?). To create a dummy script run this:
```
sudo echo "return 0" > /usr/lib/x86_64-linux-gnu/switchboard/personal/tweaks/theme-patcher
```
If this doesn't work you'll need to create the missing folders. Now try to remove the `elementary-tweaks` package again.

Bear in mind that i-hate-farm's elementary-tweaks might have patched the GTK+ theme (hence the "theme-patcher" script) on installation. Maybe you'll have to reinstall the theme.

**Comment by redstrike** [comment]
@embik Your workaround works for me. Thank you very much.

**Comment by embik** [comment]
I'm sorry but that's really nothing we can fix here, I have no idea what's the problem. Please use official support channels for elementary OS to fix that. If you can launch switchboard from terminal this sounds like another issue, but that's just a wild guess.

**Comment by teury** [comment]
sudo add-apt-repository --remove "deb http://i-hate-farms.github.io/spores trusty main"

This arranges everything

**Comment by jjoeshua** [comment]
I cant install and I cant remove Tweaks repository, when I try to remove get this error, when I try to install get error like everyone else..
sudo add-apt-repository --remove http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu 
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 107, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next

**Comment by ryonakano** [comment]
@ijoeshua Does the following command work?

```
sudo add-apt-repository -r ppa:philip.scott/elementary-tweaks
```

**Comment by jjoeshua** [comment]
trust me, please, two days I searched for solution, I also now for this command that you give me, I remove repositories before ,but this is the first time that I have problem like this, when I type this :

sudo add-apt-repository -r ppa:philip.scott/elementary-tweaks

I get this, can you help me, or explain me what is this and why? 

jjoeshua@jjoeshua:~$ sudo add-apt-repository -r ppa:philip.scott/elementary-tweaks

[sudo] password for jjoeshua:  *********
       
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 107, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next
jjoeshua@jjoeshua:~$

**Comment by jjoeshua** [comment]
I try every possible solution that I find online to install Tweaks on Ubuntu 20.4 for Pathreon, Elementary Os ,and Its not possible to install it.. 
also for removing..cant find solution..
when I type SUDO APT UPDATE, this is what I got:
jjoeshua@jjoeshua:~$ sudo apt update
[sudo] password for jjoeshua:         
Hit:1 http://repo.jztkft.hu/ubuntu focal InRelease
Hit:2 http://ppa.launchpad.net/elementary-os/daily/ubuntu focal InRelease
Hit:3 http://repo.jztkft.hu/ubuntu focal-updates InRelease                     
Hit:4 http://repo.jztkft.hu/ubuntu focal-backports InRelease                   
Hit:5 http://dl.google.com/linux/chrome/deb stable InRelease             
Hit:6 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu focal InRelease
Hit:7 http://repo.jztkft.hu/ubuntu focal-security InRelease
Hit:8 http://repo.jztkft.hu/ubuntu focal-proposed InRelease
Ign:9 http://ppa.launchpad.net/leaeasy/dde/ubuntu focal InRelease
Ign:10 http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu focal InRelease
Hit:11 http://ppa.launchpad.net/numix/ppa/ubuntu focal InRelease
Err:12 http://ppa.launchpad.net/leaeasy/dde/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Err:13 http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Get:14 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease [15,9 kB]
Err:14 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C1D89326B1C71AB9
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/leaeasy/dde/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/mpstark/elementary-tweaks-daily/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C1D89326B1C71AB9
E: The repository 'http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
jjoeshua@jjoeshua:~$

**Comment by ryonakano** [comment]
According to this line in your output,

> ```
> ptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next
> ```

you seem to run the daily version of elementary OS. elementary Tweaks does not have a PPA for Focal (see #127), and I guess this might be the cause of this problem.

I feel we can remove the PPA not by the command, but by removing the source list file. Could you run the following command and paste output here?

```
ls /etc/apt/sources.list.d/
```

**Comment by jjoeshua** [comment]
ls /etc/apt/sources.list.d/
elementary-os-ubuntu-daily-focal.list
elementary-os-ubuntu-daily-focal.list.save
elementary-os-ubuntu-os-patches-focal.list
elementary-os-ubuntu-os-patches-focal.list.save
google-chrome.list
google-chrome.list.save
leaeasy-ubuntu-dde-focal.list
leaeasy-ubuntu-dde-focal.list.save
mpstark-ubuntu-elementary-tweaks-daily-focal.list
numix-ubuntu-ppa-focal.list
numix-ubuntu-ppa-focal.list.save
philip_scott-ubuntu-elementary-tweaks-bionic.list

**Comment by ryonakano** [comment]
OK, so try the following command to force to remove the PPAs of elementary Tweaks:

```
sudo rm -f /etc/apt/sources.list.d/mpstark-ubuntu-elementary-tweaks-daily-focal.list
sudo rm -f /etc/apt/sources.list.d/philip_scott-ubuntu-elementary-tweaks-bionic.list
sudo apt update
```

**Comment by jjoeshua** [comment]
thanks for helping me,this was delete my PPAs, this is now what I get when I run Update:

jjoeshua@jjoeshua:~$ sudo rm -f /etc/apt/sources.list.d/mpstark-ubuntu-elementary-tweaks-daily-focal.list
[sudo] password for jjoeshua:         
jjoeshua@jjoeshua:~$ sudo rm -f /etc/apt/sources.list.d/philip_scott-ubuntu-elementary-tweaks-bionic.list
jjoeshua@jjoeshua:~$ sudo apt update
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 1748 (packagekitd)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /var/lib/apt/lists/
jjoeshua@jjoeshua:~$

**Comment by ryonakano** [comment]
The conventional way to use `add-apt-repository` does not work on Daily at the moment. The following way should work:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C42D52715A84C7D0D02FC740C1D89326B1C71AB9
echo -e "deb http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu focal main\n#deb-src http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/philip_scott-ubuntu-elementary-tweaks-focal.list
sudo apt update 
sudo apt install elementary-tweaks
```
