### ISSUE TITLE
Remove animation setting

### ISSUE THREAD

**Issue by danrabbit** [elementary-tweaks/elementary-tweaks#34]
This is already present in a11y > general and people are recommending adding software-properties common and all this crap just for this setting that's already in the default.

**Comment by Philip-Scott** [comment]
On one side, keeping the switch also there would keep all animation settings on one place.... but yeah, after that merge to the a11y plug it is a duplicate :( I'll think about it, if people are adding this for that setting only, perhapsthe a11y plug needs better discoverability 

_once huston is out, maybe we should add Tweaks to it :wink:_

**Comment by danrabbit** [comment]
Honestly Felipe I wish you would have let this thing die, but I'll settle with mitigating the amount of damage it causes

**Comment by Defman21** [comment]
You're rude. You could report it inmore neutral way without describing this software as crap.

**Comment by danrabbit** [comment]
Hey @Defman21 Felipe and I work together like every day. it's just friendly banter :p

**Comment by Philip-Scott** [comment]
@Defman21 Yeah, don't worry, it's all cool between us :) But thanks anyway

I'm honestly glad i picked up Tweaks though..... PPA Stats says tweaks has had about 7200 downloads, at least all that people are tweaking their system form a safe app instead of using random commands from the internet AND they are not complaining that the previous version crashes on them :wink:

**Comment by Defman21** [comment]
Oh, lol. That's explains everything. ☺
