### ISSUE TITLE
Upload to AppCenter

### ISSUE THREAD

**Issue by Focom** [elementary-tweaks/elementary-tweaks#48]
Appcenter just went public, i am sure you are already working on it but having the tweak tool there would be super handy :smiley:

**Comment by rhoconlinux** [comment]
Hope so!!! :+1: :D

**Comment by Philip-Scott** [comment]
I'll try to convince them ;) But i do see why adding it by default wouldn't be such a good idea since there are things in here that can break your system if you mess with them too much

**Comment by EricTousignant** [comment]
Here's my 2 cents, and I would love to help at some point with this project.

Why not make 2 views to the app:

*General View*
All the options that are useful, safe, etc. There could even be "profiles" like Windows or Mac settings

*Advanced View*
All the options that could break, with safe warning, etc.

Maybe that would help the elementaryOS team approve of this project?

**Comment by Focom** [comment]
Didn't know there is breaking feature. Which one is likely to break the system?

**Comment by EricTousignant** [comment]
@Focom, I can't tell what features might be breaking since I only heard this being said by the elementaryOS team disapproving of this tool. But I can tell that non advanced users would like this tool to change some easy stuff and still not be aware of the risks, hence why a way to separate the features with no risk from the ones with risk would be a good idea for this application. 

As for making it available in App Center, it's just because it would be a good idea to point new users towards resources they should trust (App Center apps) rather than what could be a bad idea if they are not power users (finding installs online, running commands, etc)

Have a great day.

**Comment by Philip-Scott** [comment]
So after a lot of consideration and talking with the rest of the team, i will not be putting the tool up on AppCenter. 

The main reason being that tweaking your system can cause bugs, specially when apps are not meant to be run with those changes

https://github.com/dahenson/agenda/issues/34
https://plus.google.com/+ErichM1/posts/3uSqW648fGH

Running the commands from a terminal should be considered like the "you accept the terms and conditions" where this tool could break your system or apps if you're not careful :)
