### ISSUE TITLE
Move plug icon to hicolor icon theme

### ISSUE THREAD

**Issue by embik** [elementary-tweaks/elementary-tweaks#7]
As noted in 6752d73, custom icons belong into `/usr/share/icons/hicolor/`. Moving the plug icon to that directory is blocked because Switchboard only loads icons from the current icon theme ([this](https://bugs.launchpad.net/switchboard/+bug/1469908) should be the corresponding upstream bug, but maybe it will be separated in the future, don't know).

This bug should remind us of checking upstream on a regular base and fix this as soon as upstream allows loading icons the proper way.

**Comment by ryonakano** [comment]
I think we can close this issue because a fix for the upstream bug was committed a long time ago and we don't see this issue anymore.

FYI we've switched the build system from CMake to Meson and all icons are set to be installed into `/usr/share/icons/hicolor/` (see https://github.com/elementary-tweaks/elementary-tweaks/blob/master/icon/meson.build). And they're shown as expected.
